export const yogaClasses = [
  {
    id: 1,
    title: "Hatha Yoga",
    description: "Hatha yoga is a classical form of yoga that focuses on physical postures.",
    cost: "$15",
    duration: "1 hour",
    difficulty: "Beginner",
    img: "https://source.unsplash.com/400x300/?yoga,hatha",
  },
  {
    id: 2,
    title: "Vinyasa Flow",
    description: "Vinyasa yoga is a dynamic practice where poses are linked together in a flowing sequence.",
    cost: "$20",
    duration: "1 hour",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,vinyasa",
  },
  {
    id: 3,
    title: "Ashtanga Yoga",
    description: "Ashtanga yoga is a vigorous and fast-paced style that follows a specific sequence of poses.",
    cost: "$18",
    duration: "1.5 hours",
    difficulty: "Advanced",
    img: "https://source.unsplash.com/400x300/?yoga,ashtanga",
  },
  {
    id: 4,
    title: "Yin Yoga",
    description: "Yin yoga is a slow-paced style where poses are held for longer periods to target the deeper connective tissues.",
    cost: "$22",
    duration: "1 hour",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,yin",
  },
  {
    id: 5,
    title: "Kundalini Yoga",
    description: "Kundalini yoga incorporates dynamic breathing techniques, meditation, and chanting to awaken the Kundalini energy.",
    cost: "$25",
    duration: "1.5 hours",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,kundalini",
  },
  {
    id: 6,
    title: "Bikram Yoga",
    description: "Bikram yoga, also known as hot yoga, consists of a series of 26 challenging poses practiced in a heated room.",
    cost: "$20",
    duration: "1.5 hours",
    difficulty: "Advanced",
    img: "https://source.unsplash.com/400x300/?yoga,bikram",
  },
  {
    id: 7,
    title: "Restorative Yoga",
    description: "Restorative yoga focuses on relaxation and stress relief through gentle poses supported by props.",
    cost: "$22",
    duration: "1 hour",
    difficulty: "Beginner",
    img: "https://source.unsplash.com/400x300/?yoga,restorative",
  },
  {
    id: 8,
    title: "Power Yoga",
    description: "Power yoga is a vigorous and fitness-based approach that emphasizes strength and flexibility.",
    cost: "$20",
    duration: "1 hour",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,power",
  },
  {
    id: 9,
    title: "Iyengar Yoga",
    description: "Iyengar yoga focuses on precise alignment and the use of props to perform poses with perfection.",
    cost: "$21",
    duration: "1 hour",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,iyengar",
  },
  {
    id: 10,
    title: "Hot Yoga",
    description: "Hot yoga is practiced in a heated room to increase sweating and detoxification.",
    cost: "$23",
    duration: "1.5 hours",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,hot",
  },
  {
    id: 11,
    title: "Acro Yoga",
    description: "Acro yoga combines acrobatics and yoga poses, often practiced with a partner.",
    cost: "$27",
    duration: "1.5 hours",
    difficulty: "Advanced",
    img: "https://source.unsplash.com/400x300/?yoga,acro",
  },
  {
    id: 12,
    title: "Chair Yoga",
    description: "Chair yoga adapts traditional yoga poses for individuals with mobility issues, practiced with the support of a chair.",
    cost: "$18",
    duration: "1 hour",
    difficulty: "Beginner",
    img: "https://source.unsplash.com/400x300/?yoga,chair",
  },
  {
    id: 13,
    title: "Prenatal Yoga",
    description: "Prenatal yoga is tailored for pregnant women to promote relaxation, reduce stress, and prepare for childbirth.",
    cost: "$24",
    duration: "1 hour",
    difficulty: "Beginner",
    img: "https://source.unsplash.com/400x300/?yoga,prenatal",
  },
  {
    id: 14,
    title: "Gentle Yoga",
    description: "Gentle yoga focuses on slow-paced movements, suitable for individuals of all fitness levels.",
    cost: "$19",
    duration: "1 hour",
    difficulty: "Beginner",
    img: "https://source.unsplash.com/400x300/?yoga,gentle",
  },
  {
    id: 15,
    title: "Pranayama",
    description: "Pranayama is the practice of breath control in yoga, which helps to regulate the flow of prana (life force energy) in the body.",
    cost: "$16",
    duration: "30 minutes",
    difficulty: "Intermediate",
    img: "https://source.unsplash.com/400x300/?yoga,pranayama",
  },
];

export default yogaClasses;
